apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-credentials-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Mi
  hostPath:
    path: /root/.aws
