[index]
endpoint = "http://127.0.0.1:4572"
bucket = "propsd"
path = "index.json"

[metadata]
host = "127.0.0.1:8080"

[consul]
scheme = "http"

[log]
level = "debug"
json = false

[properties.image]
service = "some-cool-service"
version = "1.0.0"
