apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /s3-data
