apiVersion: v1
kind: Service
metadata:
  labels:
    service: s3
    type: local
  name: s3
spec:
  ports:
  - name: "4572"
    port: 4572
    targetPort: 4572
  selector:
    service: s3
status:
  loadBalancer: {}
