apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  labels:
    io.kompose.service: metadata
  name: metadata
spec:
  selector:
    matchLabels:
      io.kompose.service: metadata
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: metadata
    spec:
      containers:
      - args:
        - metadata-mock
        - --host
        - 0.0.0.0
        image: propsd:latest
        imagePullPolicy: Never
        name: metadata
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
